### ISSUE TITLE
Cannot start scene at beginning of method

### ISSUE THREAD

**Issue by VladimirFokow** [Manim-Notebook/manim-notebook#50]
https://github.com/Manim-Notebook/manim-notebook/pull/48#issuecomment-2441775734
> 
> It seems like I am now unable to start a terminal at all on my device.

This can happen if you e.g. place your cursor here:

```py

class SquareToCircle(Scene):
    def construct(self): <--- here, on the `construct` method
        <--- or here, on empty lines just after the line with `construct` method
        <--- or here
        <--- or here
        ## Set up
        circle = Circle()
        circle.set_fill(BLUE, opacity=0.5)
        circle.set_stroke(BLUE_E, width=4)
        square = Square()
```

(the reason: the command `manimgl ... -se <this line number>` itself doesn't work with these line numbers)

<br />

The fix is easy - we just need to add this logic to `startStopScene.ts`
(I just overlooked this edge case when I wrote that.)

<br />

For example, what to do in this case:

currently: if empty lines - we check up 1 by 1

if we meet the construct method -> insert a next line and start there, e.g.:

```
        # -- manim-notebook VSCode extension: this comment was inserted automatically to start right after the "construct" method --
```

**Comment by bhoov** [comment]
I'm a bit confused, why is this? The manimgl cmd only adds the `self.embed()` method underneath the current line...

Is it because self.embed() is inserted without correct tab spacing under the construct() method? I would be that Grant implemented an insertion that simply copied the indent of the preceding line when inserting `self.embed()`

**Comment by VladimirFokow** [comment]
I don't really know why their command doesn't support that,
but we operate on an abstraction layer which uses their commands, we don't modify them

**Comment by Splines** [comment]
Do we really want to "fix" this? I mean we have identified that this has nothing to do with us, it's just a limitation of the underlying `manimgl` command that it can't start the scene at these lines. So ideally, we would fix this upstream at Manim such that it also works if you just use the command line.

Of course, for a better user experience with our extension, we could detect this case and show an error notification (instead of letting the user baffled with a cryptic error message in the terminal). In such an error notification, we could even link to an open Manim issue we have opened by then. What do you think about this?

**Comment by VladimirFokow** [comment]
I can easily do it - after finishing with you active codebase changes

**Comment by VladimirFokow** [comment]
reason for closing:
decided no to edit the user's file
